### ISSUE TITLE
Cache invalidation does not take into account files referenced by environment.yml

### ISSUE THREAD

**Issue by chrispyles** [mamba-org/setup-micromamba#113]
In ucbds-infra/otter-grader#684, I am adding two new requirements for the package in the repo's [`requirements.txt`](https://github.com/ucbds-infra/otter-grader/pull/684/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552) file. This file is referenced by the [`environment.yml`](https://github.com/ucbds-infra/otter-grader/blob/master/environment.yml#L12) file. Our action is configured to cache the mamba environment but is currently [failing](https://github.com/ucbds-infra/otter-grader/actions/runs/5707783620/job/15464793995?pr=684) because the new requirements were added to `requirements.txt` but `environment.yml` was not updated, so the setup-micromamba action assumes nothing has changed and uses the cached image.

It would be nice to be able to specify that the `environment.yml` depends on other files so that hashes of those files can also be used in the cache key, e.g.

```yaml
- uses: mamba-org/setup-micromamba@v1
  with:
    environment-file: environment.yml
    init-shell: >-
      bash
    cache-environment: true
    cache-files:
      - requirements.txt
```

Alternatively, is there a way to manually invalidate the cache for force micromamba to rebuild it?
