### ISSUE TITLE
Additional dependencies being silently ignored when using two spaces

### ISSUE THREAD

**Issue by brynpickering** [mamba-org/setup-micromamba#136]
I'm creating some actions that all start by creating a mamba environment using `setup-micromamba`. I have had no issues with it until this one random case that does not seem to be a purely `micromamba` issue.

I have one job that installs most dependencies from two requirements files, then also pins the python version and adds the `ruff` dependency in `create-args`:

``` yaml
jobs:
  memory-profiler:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: latest
          environment-name: ubuntu-latest-311
          environment-file: requirements/base.txt
          create-args: >-
            -c city-modelling-lab 
            -f requirements/dev.txt
            ruff=0.0.286
            python=3.11
          post-cleanup: all
          cache-environment: true
    ...
```

This works fine, as can be seen in e.g. [this](https://github.com/brynpickering/pam/actions/runs/6050842578/job/16420996639?pr=4) workflow run. Notably, the `ruff` dependency is installed when creating the environment.

But then I have a similar job that adds in some memory profiling dependencies in `create-args`. This [fails](https://github.com/brynpickering/pam/actions/runs/6050842578/job/16420996475?pr=4):

``` yaml
jobs:
  memory-profiler:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: latest
          environment-name: ubuntu-latest-311-memray
          environment-file: requirements/base.txt
          create-args: >-
            -c city-modelling-lab 
            -f requirements/dev.txt
            memray=1.9.1
            pytest-memray=1.5.0
            python=3.11
          post-cleanup: all
          cache-environment: true
    ...
```

This second case is mysterious, because it translates to the correct micromamba call: 

``` bash
/home/runner/micromamba-bin/micromamba create -y -r /home/runner/micromamba -f requirements/base.txt -n ubuntu-latest-311-memray -c city-modelling-lab  -f requirements/dev.txt memray=1.9.1 pytest-memray=1.5.0 python=3.11 --log-level warning --rc-file /home/runner/micromamba-bin/.condarc
```

But then `memray` and `pytest-memray` are _not_ in the full list of installed packages under `micromamba list`.

Running the call locally creates the expected environment, i.e. including `memray`.

**Comment by jonashaag** [comment]
Is it because the list is run in the first environment?

Can you link to a run that shows this problem please?

**Comment by pavelzw** [comment]
[this](https://github.com/brynpickering/pam/actions/runs/6050842578/job/16420996475?pr=4) run shows the issue @jonashaag 

<img width="922" alt="image" src="https://github.com/mamba-org/setup-micromamba/assets/29506042/89b63e66-e4e9-48ef-aa88-a441670e609b">
<img width="774" alt="image" src="https://github.com/mamba-org/setup-micromamba/assets/29506042/5804ba4f-8738-4ab8-9f8b-f44007966e1d">
no memray to be seen :/

**Comment by pavelzw** [comment]
Can you try to rerun again with `cache-environment: false` @brynpickering ? This might have something to do with incorrect cache invalidation...

**Comment by pavelzw** [comment]
This seems like a mamba problem... @jonashaag do you know if multiple dependency files are supported by micromamba?

**Comment by pavelzw** [comment]
> Running the call locally creates the expected environment, i.e. including memray.

Did you also try it out manually in CI? i.e. run
```yml
- uses: mamba-org/setup-micromamba@v1
- run: /home/runner/micromamba-bin/micromamba create -y -r /home/runner/micromamba -f requirements/base.txt -n ubuntu-latest-311-memray -c city-modelling-lab  -f requirements/dev.txt memray=1.9.1 pytest-memray=1.5.0 python=3.11 --log-level warning --rc-file /home/runner/micromamba-bin/.condarc
- run: |
    micromamba activate ubuntu-latest-311-memray
    micromamba list
  shell: bash -el {0}
```
