### ISSUE TITLE
Support selectors

### ISSUE THREAD

**Issue by tdegeus** [mamba-org/setup-micromamba#162]
I would like to
```yaml
- name: Create conda environment
  uses: mamba-org/setup-micromamba@main
  with:
    environment-file: environment.yaml
    environment-name: myenv
    init-shell: bash
    cache-downloads: true
    post-cleanup: all
    create-args: |
      sel(win): clang_win-64
```
but that does not seem to be supported any longer

**Comment by pavelzw** [comment]
How about something like

```yml
- name: Create conda environment
  uses: mamba-org/setup-micromamba@main
  with:
    environment-file: environment.yaml
    environment-name: myenv
    init-shell: bash
    cache-downloads: true
    post-cleanup: all
    create-args: |
      ${{ runner.os == 'Windows' && 'clang_win-64' || '' }}
```

(untested)

Alternatively, you should still be able to add selectors to `environment.yaml`.
