### ISSUE TITLE
Error when extracting package

### ISSUE THREAD

**Issue by tudoroancea** [mamba-org/setup-micromamba#263]
Hi everyone, 

I recently tried to setup a CI workflow using `setup-micromamba`  and got [a very weird error](https://github.com/tudoroancea/brains2/actions/runs/13409840505/job/37457268845?pr=65).

For reference, here is the workflow config I wrote:
```yaml
  build:
    name: Build with micromamba (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    if: github.event.label.name == 'run_build_ci'
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v4
        with:
          recursive: true

      - name: Remove workflow label
        run: gh pr edit ${{ github.event.pull_request.number }} --remove-label run_build_ci
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: conda-lock.yml
          environment-name: brains2
          init-shell: bash

      - name: Build workspace
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh

```

I am troubled by the fact that `micromamba` actually is able to correctly read the dependencies in `conda-lock.yml` and just fails on the first download.
I find the non-ascii characters in the error message fishy. Could they be the reason why the downloaded file can't be properly extracted?
