### ISSUE TITLE
Error: EPERM: operation not permitted, unlink 'C:\Users\runneradmin\micromamba\pkgs\libzlib-1.3.1-h2466b09_2\zlib.dll'

### ISSUE THREAD

**Issue by mrclary** [mamba-org/setup-micromamba#268]
This error suddenly appeared today in https://github.com/spyder-ide/spyder Workflows at the teardown of the `setup-micromamba` action:
`Error: EPERM: operation not permitted, unlink 'C:\Users\runneradmin\micromamba\pkgs\libzlib-1.3.1-h2466b09_2\zlib.dll'`

For full run with debug log: https://github.com/spyder-ide/spyder/actions/runs/14340936403/job/40208867170

Any insight about what is causing this and how to prevent it?

**Comment by pavelzw** [comment]
Most likely some process is still holding a lock on this file which leads to an error while the action is trying to remove it.

You can skip the removing part by specifying `post-cleanup: none`.

**Comment by mrclary** [comment]
@pavelzw, thanks for your prompt response! Just a followup...
Our workflows are working again today and I'm now noticing a difference.

The failed workflows all report `Removing uncompressed packages to trim down cache folder...`; This appears to be the proximate cause of the issue, as you mentioned, that there is a lock on some files that the cleanup action is trying to remove.

The successful workflows only report `Deinitialize micromamba for bash`, which is the default cleanup action if `post-cleanup` is not specified.

So, it seems that the error may be related to the caching process. Will `post-cleanup: none` still allow caching? If so, might this error still resurface? Or perhaps we are not using the cache feature properly? Our relevant workflow step is:
```
- name: Create conda test environment
  if: env.USE_CONDA == 'true'
  uses: mamba-org/setup-micromamba@v1
  with:
    micromamba-version: '1.5.10-0'
    environment-file: requirements/main.yml
    environment-name: test
    cache-downloads: true
    create-args: python=${{ matrix.PYTHON_VERSION }}
```
