### ISSUE TITLE
Better argument parsing for `create-args` and `shell-init`

### ISSUE THREAD

**Issue by pavelzw** [mamba-org/setup-micromamba#42]
Currently, the actions expects a string that looks like a JSON array, i.e., `init-shell: '["bash", "cmd.exe"]'`. 
Multiline syntax would be better
```yml
uses: mamba-org/setup-micromamba@v1
with:
  init-shell: |
    bash
    cmd.exe
```
