### ISSUE TITLE
Setup micromamba once, but install and use multiple envs (allow setup without creating an env?)

### ISSUE THREAD

**Issue by MikulasZelinka** [mamba-org/setup-micromamba#51]
Hello, I'd like to achieve the following:

1. `micromamba` is setup once (and bash is initialised, as is already the default)
2. we install multiple empty envs with different python versions
3. we install a custom python package and run pytest in each of the different envs

I have this so far:

```yml
name: Testing (pytest)

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - uses: mamba-org/setup-micromamba@v1.1.0
        with:
          environment-name: ${{ matrix.python-version }}
          create-args: python=${{ matrix.python-version }}

      - name: test
        run: |
          micromamba activate ${{ matrix.python-version }}
          pip install .
          pip install pytest
          pytest

```

Now this works, however, `micromamba` is installed four times.

I would like to install it just once and avoid writing default envs to bashrc (although that's not as important, because we can just get around that by using `activate`).

For example, if there was a way to just not install any env when setting micromamba up, I could just set up micromamba once without the matrix and then manually install the different envs in a shell.

**Comment by pavelzw** [comment]
When you don't specify anything, the action doesn't set up an environment.

You could do something like this:

```yml
name: Testing (pytest)

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - uses: mamba-org/setup-micromamba@v1.1.0
      - name: test 3.8
        run: |
          micromamba create -n 3.8 python=3.8 pytest
          micromamba activate 3.8
          pip install .
          pytest
      ...
```
