### ISSUE TITLE
Auto-activating environment does not work when --name argument was passed to environment activation

### ISSUE THREAD

**Issue by JohannesWiesner** [mamba-org/setup-micromamba#71]
I use the following commands to specify a name for an environment that I want to create using a `.yml` file:

```yml
    - name: setup micromamba and solve environment
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        create-args: --name test_micromamba
```

The `.yml` file already has a `name: csp_surname_name` attribute that I explicitly want to overwrite using the `--name` argument in `create-args:`. Everything works fine and the name gets overwritten, but when the workflow reaches the "auto-activation" step it seems to not be aware of the new name but uses the one in `.yml` file. Of course, an environment with this name does not exist at this point so the workflow crashes here:

![image](https://github.com/mamba-org/setup-micromamba/assets/48254290/3d54e085-f597-40b1-9b84-59697cea8722)
