### ISSUE TITLE
Possible to export pip-packages?

### ISSUE THREAD

**Issue by JohannesWiesner** [mamba-org/setup-micromamba#75]
I am using `setup-micromamba@v1` to create environments and would like to export them as text files, either with `micromamba env export --name ... > file.yml` or `conda list --explicit > file.txt`. However, I noticed that pip-packages are not included in the exported text files. Is this behavior normal?

Here's an [example repo](https://github.com/JohannesWiesner/test_push_yml/blob/main/.github/workflows/run-github-workflows.yml) where I use the workflow to create an environment based on the input file `environment.yml`, export it to text files and then push it back to the repo (the two files with `_solved` as suffixes).

**Comment by jonashaag** [comment]
See https://github.com/mamba-org/mamba/issues/2008

**Comment by pavelzw** [comment]
For now, you could do something like this:

```yml
- name: setup micromamba and solve environment
  uses: mamba-org/setup-micromamba@v1
  with:
    environment-file: environment.yml
    environment-name: ${{ runner.os }}
- name: export environment created with micromamba using conda
  run: |
    conda env export -p "${MAMBA_ROOT_PREFIX}/envs/${{ runner.os }}" > ./environments/${{ runner.os }}_solved_with_pip.yml
```

Btw `conda list --explicit` can be replaced by `micromamba env export --explicit`.
