### ISSUE TITLE
Setup multiple environments in order to activate them with --stack

### ISSUE THREAD

**Issue by pmav99** [mamba-org/setup-micromamba#76]
This is somewhat similar to #51 but the idea now is to be able to setup multiple environments instead of just one in order to be able to use stack them using `activate --stack`.

**Comment by pavelzw** [comment]
Hmm, I think this use case is too _niche_ to be implemented in this action. But you can install the second environment separately and add the `activate --stack` to the bashrc yourself.

```yml
- uses: mamba-org/setup-micromamba@v1
  with:
    environment-name: env1
    environment-file: environment1.yml
- name: Install second environment
  run: |
    micromamba create -f environment2.yml -n env2 -y
    echo "micromamba activate --stack env2" >> ~/.bashrc
  shell: bash -el {0}
...
- name: Clean up bashrc
  # only relevant for self hosted runners that persist ~/.bashrc
  run: sed -i '/^micromamba activate --stack env2$/d' ~/.bashrc
```

**Comment by jonashaag** [comment]
Agreed. You could also have it not install any environment at all, just the executable.

**Comment by pavelzw** [comment]
This would look like this then:
```yml
- uses: mamba-org/setup-micromamba@v1
- name: Install second environment
  run: |
    micromamba create -f environment1.yml -n env1 -y
    micromamba create -f environment2.yml -n env2 -y
    echo "micromamba activate env1" >> ~/.bashrc
    echo "micromamba activate --stack env2" >> ~/.bashrc
  shell: bash -el {0}
...
- name: Clean up bashrc
  # only relevant for self hosted runners that persist ~/.bashrc
  run: |
    sed -i '/^micromamba activate env1$/d' ~/.bashrc
    sed -i '/^micromamba activate --stack env2$/d' ~/.bashrc
```

**Comment by pmav99** [comment]
I agree that it is somewhat niche. 

The point of integrating this to the github action is to take advantage of the caching mechanics. The way I was thinking this could be implemented would be something like:
``` yaml
- uses: mamba-org/setup-micromamba@v1
  with:
    environment-file: 
        - environment1.yml
        - environment2.yml
```
While the environment names must be specified within the environment files and the order of activation is the order of the environment files. 

But I do understand that it will complicate both the API and the implementation. I thought it wouldn't hurt to mention it though.

Feel free to close the issue and thanks for the suggestions

**Comment by pavelzw** [comment]
> to take advantage of the caching mechanics

You can also implement caching on your own, it's not really complicated :)

```yml
- uses: mamba-org/setup-micromamba@v1
- uses: actions/cache@v3
  with:
    path: |
      ~/micromamba/envs/env1
      ~/micromamba/envs/env2
    key: ${{ hashFiles('environment1.yml', 'environment2.yml') }}
  id: cache-envs
- name: Install second environment
  run: |
    micromamba create -f environment1.yml -n env1 -y
    micromamba create -f environment2.yml -n env2 -y
  shell: bash -el {0}
  if: steps.cache-envs.outputs.cache-hit != 'true'
- name: Add auto activation
  run: |
    echo "micromamba activate env1" >> ~/.bashrc
    echo "micromamba activate --stack env2" >> ~/.bashrc
```

Something like this _should_ work, maybe you would want to add the date to the cache key for automatic invalidation after some time
