### ISSUE TITLE
Windows: micromamba not a valid command

### ISSUE THREAD

**Issue by jdegenstein** [mamba-org/setup-micromamba#86]
I am trying to migrate from provision-micromamba to setup-micromamba and running to an issue only on my Windows runners. For some reason when the runner attempts to execute `micromamba info` I get the following error:

`micromamba : The term 'micromamba' is not recognized as the name of a cmdlet, function, script file, or operable ...`

I have tried to initialize powershell, but that did not seem to help.
```yml
...
build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: test
        environment-file: environment.yml
        init-shell: >-
            powershell
        create-args: >-
            python=3.10
    - name: pip install cadquery CQ-editor ... etc
      shell: powershell
...
```

Full source file here:
https://github.com/jdegenstein/jmwright-CQ-Editor/blob/main/.github/workflows/pyinstaller-builds-actions-PIP-TAR.yml
