### ISSUE TITLE
Issue with package specification in create-args

### ISSUE THREAD

**Issue by sblauth** [mamba-org/setup-micromamba#88]
I have a problem / unexpected behavior when using `create-args` and specifying a package restriction.
E.g., if I use the following code in my "old" setting:

```
- name: Install micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: .github/micromamba/testenv.yml
        extra-specs: |
          gmsh">=4.8"
```
to specify that gmsh with version <= 4.8 has to be used.

When I switch to `setup-micromamba`, I use the following analogous code
```
- name: Install micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: .github/micromamba/testenv.yml
        create-args: >-
          gmsh">=4.8"
```
but this raises an error. If I drop the quotation marks and use the code
```
- name: Install micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: .github/micromamba/testenv.yml
        create-args: >-
          gmsh>=4.8
```
everything works fine. I think this issue should at least be documented somewhere, or the usual `conda` syntax (with quotation marks) should work here.
